baseURL = 'https://jayrovacsek.github.io/ncsg-presentation-october-2024/#/'
languageCode = 'en-au'
title = 'ncsg-presentation-october-2024'
theme = ["github.com/dzello/reveal-hugo"]

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true
hideInactiveCursor = true
theme = "blood"
slide_number = true
transition_speed = 'fast'

[markup.goldmark.extensions.extras.superscript]
enable = true
